// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test_DEF int32

const (
	Test_ID Test_DEF = 1001
)

var Test_DEF_name = map[int32]string{
	1001: "ID",
}

var Test_DEF_value = map[string]int32{
	"ID": 1001,
}

func (x Test_DEF) Enum() *Test_DEF {
	p := new(Test_DEF)
	*p = x
	return p
}

func (x Test_DEF) String() string {
	return proto.EnumName(Test_DEF_name, int32(x))
}

func (x *Test_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Test_DEF_value, data, "Test_DEF")
	if err != nil {
		return err
	}
	*x = Test_DEF(value)
	return nil
}

func (Test_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0, 0}
}

type Test struct {
	StrTest              *string  `protobuf:"bytes,1,req,name=strTest" json:"strTest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetStrTest() string {
	if m != nil && m.StrTest != nil {
		return *m.StrTest
	}
	return ""
}

func init() {
	proto.RegisterEnum("example.Test_DEF", Test_DEF_name, Test_DEF_value)
	proto.RegisterType((*Test)(nil), "example.Test")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55,
	0x32, 0xe0, 0x62, 0x09, 0x49, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x2e, 0x29, 0x02, 0x31,
	0x25, 0x18, 0x15, 0x98, 0x34, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x3e, 0x2e, 0x66, 0x17, 0x57, 0x37,
	0x21, 0x76, 0x2e, 0x26, 0x4f, 0x17, 0x81, 0x97, 0xec, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58,
	0xb0, 0x41, 0x26, 0x47, 0x00, 0x00, 0x00,
}
