// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq_DEF int32

const (
	LoginReq_ID LoginReq_DEF = 1
)

var LoginReq_DEF_name = map[int32]string{
	1: "ID",
}

var LoginReq_DEF_value = map[string]int32{
	"ID": 1,
}

func (x LoginReq_DEF) Enum() *LoginReq_DEF {
	p := new(LoginReq_DEF)
	*p = x
	return p
}

func (x LoginReq_DEF) String() string {
	return proto.EnumName(LoginReq_DEF_name, int32(x))
}

func (x *LoginReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginReq_DEF_value, data, "LoginReq_DEF")
	if err != nil {
		return err
	}
	*x = LoginReq_DEF(value)
	return nil
}

func (LoginReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{0, 0}
}

type LoginResp_DEF int32

const (
	LoginResp_ID LoginResp_DEF = 2
)

var LoginResp_DEF_name = map[int32]string{
	2: "ID",
}

var LoginResp_DEF_value = map[string]int32{
	"ID": 2,
}

func (x LoginResp_DEF) Enum() *LoginResp_DEF {
	p := new(LoginResp_DEF)
	*p = x
	return p
}

func (x LoginResp_DEF) String() string {
	return proto.EnumName(LoginResp_DEF_name, int32(x))
}

func (x *LoginResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginResp_DEF_value, data, "LoginResp_DEF")
	if err != nil {
		return err
	}
	*x = LoginResp_DEF(value)
	return nil
}

func (LoginResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{1, 0}
}

type ResetReq_DEF int32

const (
	ResetReq_ID ResetReq_DEF = 20
)

var ResetReq_DEF_name = map[int32]string{
	20: "ID",
}

var ResetReq_DEF_value = map[string]int32{
	"ID": 20,
}

func (x ResetReq_DEF) Enum() *ResetReq_DEF {
	p := new(ResetReq_DEF)
	*p = x
	return p
}

func (x ResetReq_DEF) String() string {
	return proto.EnumName(ResetReq_DEF_name, int32(x))
}

func (x *ResetReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResetReq_DEF_value, data, "ResetReq_DEF")
	if err != nil {
		return err
	}
	*x = ResetReq_DEF(value)
	return nil
}

func (ResetReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{2, 0}
}

type ResetResp_DEF int32

const (
	ResetResp_ID ResetResp_DEF = 21
)

var ResetResp_DEF_name = map[int32]string{
	21: "ID",
}

var ResetResp_DEF_value = map[string]int32{
	"ID": 21,
}

func (x ResetResp_DEF) Enum() *ResetResp_DEF {
	p := new(ResetResp_DEF)
	*p = x
	return p
}

func (x ResetResp_DEF) String() string {
	return proto.EnumName(ResetResp_DEF_name, int32(x))
}

func (x *ResetResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResetResp_DEF_value, data, "ResetResp_DEF")
	if err != nil {
		return err
	}
	*x = ResetResp_DEF(value)
	return nil
}

func (ResetResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{3, 0}
}

type FastLoginReq_DEF int32

const (
	FastLoginReq_ID FastLoginReq_DEF = 3
)

var FastLoginReq_DEF_name = map[int32]string{
	3: "ID",
}

var FastLoginReq_DEF_value = map[string]int32{
	"ID": 3,
}

func (x FastLoginReq_DEF) Enum() *FastLoginReq_DEF {
	p := new(FastLoginReq_DEF)
	*p = x
	return p
}

func (x FastLoginReq_DEF) String() string {
	return proto.EnumName(FastLoginReq_DEF_name, int32(x))
}

func (x *FastLoginReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FastLoginReq_DEF_value, data, "FastLoginReq_DEF")
	if err != nil {
		return err
	}
	*x = FastLoginReq_DEF(value)
	return nil
}

func (FastLoginReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{4, 0}
}

type FastLoginResp_DEF int32

const (
	FastLoginResp_ID FastLoginResp_DEF = 4
)

var FastLoginResp_DEF_name = map[int32]string{
	4: "ID",
}

var FastLoginResp_DEF_value = map[string]int32{
	"ID": 4,
}

func (x FastLoginResp_DEF) Enum() *FastLoginResp_DEF {
	p := new(FastLoginResp_DEF)
	*p = x
	return p
}

func (x FastLoginResp_DEF) String() string {
	return proto.EnumName(FastLoginResp_DEF_name, int32(x))
}

func (x *FastLoginResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FastLoginResp_DEF_value, data, "FastLoginResp_DEF")
	if err != nil {
		return err
	}
	*x = FastLoginResp_DEF(value)
	return nil
}

func (FastLoginResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{5, 0}
}

type GetVerifyCodeReq_DEF int32

const (
	GetVerifyCodeReq_ID GetVerifyCodeReq_DEF = 7
)

var GetVerifyCodeReq_DEF_name = map[int32]string{
	7: "ID",
}

var GetVerifyCodeReq_DEF_value = map[string]int32{
	"ID": 7,
}

func (x GetVerifyCodeReq_DEF) Enum() *GetVerifyCodeReq_DEF {
	p := new(GetVerifyCodeReq_DEF)
	*p = x
	return p
}

func (x GetVerifyCodeReq_DEF) String() string {
	return proto.EnumName(GetVerifyCodeReq_DEF_name, int32(x))
}

func (x *GetVerifyCodeReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetVerifyCodeReq_DEF_value, data, "GetVerifyCodeReq_DEF")
	if err != nil {
		return err
	}
	*x = GetVerifyCodeReq_DEF(value)
	return nil
}

func (GetVerifyCodeReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{6, 0}
}

type GetVerifyCodeResp_DEF int32

const (
	GetVerifyCodeResp_ID GetVerifyCodeResp_DEF = 8
)

var GetVerifyCodeResp_DEF_name = map[int32]string{
	8: "ID",
}

var GetVerifyCodeResp_DEF_value = map[string]int32{
	"ID": 8,
}

func (x GetVerifyCodeResp_DEF) Enum() *GetVerifyCodeResp_DEF {
	p := new(GetVerifyCodeResp_DEF)
	*p = x
	return p
}

func (x GetVerifyCodeResp_DEF) String() string {
	return proto.EnumName(GetVerifyCodeResp_DEF_name, int32(x))
}

func (x *GetVerifyCodeResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetVerifyCodeResp_DEF_value, data, "GetVerifyCodeResp_DEF")
	if err != nil {
		return err
	}
	*x = GetVerifyCodeResp_DEF(value)
	return nil
}

func (GetVerifyCodeResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{7, 0}
}

type RegisterReq_DEF int32

const (
	RegisterReq_ID RegisterReq_DEF = 9
)

var RegisterReq_DEF_name = map[int32]string{
	9: "ID",
}

var RegisterReq_DEF_value = map[string]int32{
	"ID": 9,
}

func (x RegisterReq_DEF) Enum() *RegisterReq_DEF {
	p := new(RegisterReq_DEF)
	*p = x
	return p
}

func (x RegisterReq_DEF) String() string {
	return proto.EnumName(RegisterReq_DEF_name, int32(x))
}

func (x *RegisterReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterReq_DEF_value, data, "RegisterReq_DEF")
	if err != nil {
		return err
	}
	*x = RegisterReq_DEF(value)
	return nil
}

func (RegisterReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{8, 0}
}

type RegisterResp_DEF int32

const (
	RegisterResp_ID RegisterResp_DEF = 10
)

var RegisterResp_DEF_name = map[int32]string{
	10: "ID",
}

var RegisterResp_DEF_value = map[string]int32{
	"ID": 10,
}

func (x RegisterResp_DEF) Enum() *RegisterResp_DEF {
	p := new(RegisterResp_DEF)
	*p = x
	return p
}

func (x RegisterResp_DEF) String() string {
	return proto.EnumName(RegisterResp_DEF_name, int32(x))
}

func (x *RegisterResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterResp_DEF_value, data, "RegisterResp_DEF")
	if err != nil {
		return err
	}
	*x = RegisterResp_DEF(value)
	return nil
}

func (RegisterResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{9, 0}
}

type ConnectGameServerReq_DEF int32

const (
	ConnectGameServerReq_ID ConnectGameServerReq_DEF = 40
)

var ConnectGameServerReq_DEF_name = map[int32]string{
	40: "ID",
}

var ConnectGameServerReq_DEF_value = map[string]int32{
	"ID": 40,
}

func (x ConnectGameServerReq_DEF) Enum() *ConnectGameServerReq_DEF {
	p := new(ConnectGameServerReq_DEF)
	*p = x
	return p
}

func (x ConnectGameServerReq_DEF) String() string {
	return proto.EnumName(ConnectGameServerReq_DEF_name, int32(x))
}

func (x *ConnectGameServerReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConnectGameServerReq_DEF_value, data, "ConnectGameServerReq_DEF")
	if err != nil {
		return err
	}
	*x = ConnectGameServerReq_DEF(value)
	return nil
}

func (ConnectGameServerReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{10, 0}
}

type ConnectGameServerResp_DEF int32

const (
	ConnectGameServerResp_ID ConnectGameServerResp_DEF = 41
)

var ConnectGameServerResp_DEF_name = map[int32]string{
	41: "ID",
}

var ConnectGameServerResp_DEF_value = map[string]int32{
	"ID": 41,
}

func (x ConnectGameServerResp_DEF) Enum() *ConnectGameServerResp_DEF {
	p := new(ConnectGameServerResp_DEF)
	*p = x
	return p
}

func (x ConnectGameServerResp_DEF) String() string {
	return proto.EnumName(ConnectGameServerResp_DEF_name, int32(x))
}

func (x *ConnectGameServerResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConnectGameServerResp_DEF_value, data, "ConnectGameServerResp_DEF")
	if err != nil {
		return err
	}
	*x = ConnectGameServerResp_DEF(value)
	return nil
}

func (ConnectGameServerResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{11, 0}
}

type HeartbeatReq_DEF int32

const (
	HeartbeatReq_ID HeartbeatReq_DEF = 100
)

var HeartbeatReq_DEF_name = map[int32]string{
	100: "ID",
}

var HeartbeatReq_DEF_value = map[string]int32{
	"ID": 100,
}

func (x HeartbeatReq_DEF) Enum() *HeartbeatReq_DEF {
	p := new(HeartbeatReq_DEF)
	*p = x
	return p
}

func (x HeartbeatReq_DEF) String() string {
	return proto.EnumName(HeartbeatReq_DEF_name, int32(x))
}

func (x *HeartbeatReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HeartbeatReq_DEF_value, data, "HeartbeatReq_DEF")
	if err != nil {
		return err
	}
	*x = HeartbeatReq_DEF(value)
	return nil
}

func (HeartbeatReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{12, 0}
}

type HeartbeatResp_DEF int32

const (
	HeartbeatResp_ID HeartbeatResp_DEF = 101
)

var HeartbeatResp_DEF_name = map[int32]string{
	101: "ID",
}

var HeartbeatResp_DEF_value = map[string]int32{
	"ID": 101,
}

func (x HeartbeatResp_DEF) Enum() *HeartbeatResp_DEF {
	p := new(HeartbeatResp_DEF)
	*p = x
	return p
}

func (x HeartbeatResp_DEF) String() string {
	return proto.EnumName(HeartbeatResp_DEF_name, int32(x))
}

func (x *HeartbeatResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HeartbeatResp_DEF_value, data, "HeartbeatResp_DEF")
	if err != nil {
		return err
	}
	*x = HeartbeatResp_DEF(value)
	return nil
}

func (HeartbeatResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{13, 0}
}

type GetServerTimeReq_DEF int32

const (
	GetServerTimeReq_ID GetServerTimeReq_DEF = 106
)

var GetServerTimeReq_DEF_name = map[int32]string{
	106: "ID",
}

var GetServerTimeReq_DEF_value = map[string]int32{
	"ID": 106,
}

func (x GetServerTimeReq_DEF) Enum() *GetServerTimeReq_DEF {
	p := new(GetServerTimeReq_DEF)
	*p = x
	return p
}

func (x GetServerTimeReq_DEF) String() string {
	return proto.EnumName(GetServerTimeReq_DEF_name, int32(x))
}

func (x *GetServerTimeReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetServerTimeReq_DEF_value, data, "GetServerTimeReq_DEF")
	if err != nil {
		return err
	}
	*x = GetServerTimeReq_DEF(value)
	return nil
}

func (GetServerTimeReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{14, 0}
}

type GetServerTimeResp_DEF int32

const (
	GetServerTimeResp_ID GetServerTimeResp_DEF = 107
)

var GetServerTimeResp_DEF_name = map[int32]string{
	107: "ID",
}

var GetServerTimeResp_DEF_value = map[string]int32{
	"ID": 107,
}

func (x GetServerTimeResp_DEF) Enum() *GetServerTimeResp_DEF {
	p := new(GetServerTimeResp_DEF)
	*p = x
	return p
}

func (x GetServerTimeResp_DEF) String() string {
	return proto.EnumName(GetServerTimeResp_DEF_name, int32(x))
}

func (x *GetServerTimeResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetServerTimeResp_DEF_value, data, "GetServerTimeResp_DEF")
	if err != nil {
		return err
	}
	*x = GetServerTimeResp_DEF(value)
	return nil
}

func (GetServerTimeResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{15, 0}
}

type QuitGameServerReq_DEF int32

const (
	QuitGameServerReq_ID QuitGameServerReq_DEF = 110
)

var QuitGameServerReq_DEF_name = map[int32]string{
	110: "ID",
}

var QuitGameServerReq_DEF_value = map[string]int32{
	"ID": 110,
}

func (x QuitGameServerReq_DEF) Enum() *QuitGameServerReq_DEF {
	p := new(QuitGameServerReq_DEF)
	*p = x
	return p
}

func (x QuitGameServerReq_DEF) String() string {
	return proto.EnumName(QuitGameServerReq_DEF_name, int32(x))
}

func (x *QuitGameServerReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QuitGameServerReq_DEF_value, data, "QuitGameServerReq_DEF")
	if err != nil {
		return err
	}
	*x = QuitGameServerReq_DEF(value)
	return nil
}

func (QuitGameServerReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{16, 0}
}

type QuitGameServerResp_DEF int32

const (
	QuitGameServerResp_ID QuitGameServerResp_DEF = 111
)

var QuitGameServerResp_DEF_name = map[int32]string{
	111: "ID",
}

var QuitGameServerResp_DEF_value = map[string]int32{
	"ID": 111,
}

func (x QuitGameServerResp_DEF) Enum() *QuitGameServerResp_DEF {
	p := new(QuitGameServerResp_DEF)
	*p = x
	return p
}

func (x QuitGameServerResp_DEF) String() string {
	return proto.EnumName(QuitGameServerResp_DEF_name, int32(x))
}

func (x *QuitGameServerResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QuitGameServerResp_DEF_value, data, "QuitGameServerResp_DEF")
	if err != nil {
		return err
	}
	*x = QuitGameServerResp_DEF(value)
	return nil
}

func (QuitGameServerResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{17, 0}
}

type OnlineReq_DEF int32

const (
	OnlineReq_ID OnlineReq_DEF = 120
)

var OnlineReq_DEF_name = map[int32]string{
	120: "ID",
}

var OnlineReq_DEF_value = map[string]int32{
	"ID": 120,
}

func (x OnlineReq_DEF) Enum() *OnlineReq_DEF {
	p := new(OnlineReq_DEF)
	*p = x
	return p
}

func (x OnlineReq_DEF) String() string {
	return proto.EnumName(OnlineReq_DEF_name, int32(x))
}

func (x *OnlineReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OnlineReq_DEF_value, data, "OnlineReq_DEF")
	if err != nil {
		return err
	}
	*x = OnlineReq_DEF(value)
	return nil
}

func (OnlineReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{18, 0}
}

type OnlineResp_DEF int32

const (
	OnlineResp_ID OnlineResp_DEF = 121
)

var OnlineResp_DEF_name = map[int32]string{
	121: "ID",
}

var OnlineResp_DEF_value = map[string]int32{
	"ID": 121,
}

func (x OnlineResp_DEF) Enum() *OnlineResp_DEF {
	p := new(OnlineResp_DEF)
	*p = x
	return p
}

func (x OnlineResp_DEF) String() string {
	return proto.EnumName(OnlineResp_DEF_name, int32(x))
}

func (x *OnlineResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OnlineResp_DEF_value, data, "OnlineResp_DEF")
	if err != nil {
		return err
	}
	*x = OnlineResp_DEF(value)
	return nil
}

func (OnlineResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{19, 0}
}

type OfflineReq_DEF int32

const (
	OfflineReq_ID OfflineReq_DEF = 130
)

var OfflineReq_DEF_name = map[int32]string{
	130: "ID",
}

var OfflineReq_DEF_value = map[string]int32{
	"ID": 130,
}

func (x OfflineReq_DEF) Enum() *OfflineReq_DEF {
	p := new(OfflineReq_DEF)
	*p = x
	return p
}

func (x OfflineReq_DEF) String() string {
	return proto.EnumName(OfflineReq_DEF_name, int32(x))
}

func (x *OfflineReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OfflineReq_DEF_value, data, "OfflineReq_DEF")
	if err != nil {
		return err
	}
	*x = OfflineReq_DEF(value)
	return nil
}

func (OfflineReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{20, 0}
}

type OfflineResp_DEF int32

const (
	OfflineResp_ID OfflineResp_DEF = 131
)

var OfflineResp_DEF_name = map[int32]string{
	131: "ID",
}

var OfflineResp_DEF_value = map[string]int32{
	"ID": 131,
}

func (x OfflineResp_DEF) Enum() *OfflineResp_DEF {
	p := new(OfflineResp_DEF)
	*p = x
	return p
}

func (x OfflineResp_DEF) String() string {
	return proto.EnumName(OfflineResp_DEF_name, int32(x))
}

func (x *OfflineResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OfflineResp_DEF_value, data, "OfflineResp_DEF")
	if err != nil {
		return err
	}
	*x = OfflineResp_DEF(value)
	return nil
}

func (OfflineResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{21, 0}
}

type CheckUpgradeReq_DEF int32

const (
	CheckUpgradeReq_ID CheckUpgradeReq_DEF = 150
)

var CheckUpgradeReq_DEF_name = map[int32]string{
	150: "ID",
}

var CheckUpgradeReq_DEF_value = map[string]int32{
	"ID": 150,
}

func (x CheckUpgradeReq_DEF) Enum() *CheckUpgradeReq_DEF {
	p := new(CheckUpgradeReq_DEF)
	*p = x
	return p
}

func (x CheckUpgradeReq_DEF) String() string {
	return proto.EnumName(CheckUpgradeReq_DEF_name, int32(x))
}

func (x *CheckUpgradeReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CheckUpgradeReq_DEF_value, data, "CheckUpgradeReq_DEF")
	if err != nil {
		return err
	}
	*x = CheckUpgradeReq_DEF(value)
	return nil
}

func (CheckUpgradeReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{22, 0}
}

type CheckUpgradeResp_DEF int32

const (
	CheckUpgradeResp_ID CheckUpgradeResp_DEF = 151
)

var CheckUpgradeResp_DEF_name = map[int32]string{
	151: "ID",
}

var CheckUpgradeResp_DEF_value = map[string]int32{
	"ID": 151,
}

func (x CheckUpgradeResp_DEF) Enum() *CheckUpgradeResp_DEF {
	p := new(CheckUpgradeResp_DEF)
	*p = x
	return p
}

func (x CheckUpgradeResp_DEF) String() string {
	return proto.EnumName(CheckUpgradeResp_DEF_name, int32(x))
}

func (x *CheckUpgradeResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CheckUpgradeResp_DEF_value, data, "CheckUpgradeResp_DEF")
	if err != nil {
		return err
	}
	*x = CheckUpgradeResp_DEF(value)
	return nil
}

func (CheckUpgradeResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{23, 0}
}

type GameResUpgradeReq_DEF int32

const (
	GameResUpgradeReq_ID GameResUpgradeReq_DEF = 13
)

var GameResUpgradeReq_DEF_name = map[int32]string{
	13: "ID",
}

var GameResUpgradeReq_DEF_value = map[string]int32{
	"ID": 13,
}

func (x GameResUpgradeReq_DEF) Enum() *GameResUpgradeReq_DEF {
	p := new(GameResUpgradeReq_DEF)
	*p = x
	return p
}

func (x GameResUpgradeReq_DEF) String() string {
	return proto.EnumName(GameResUpgradeReq_DEF_name, int32(x))
}

func (x *GameResUpgradeReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameResUpgradeReq_DEF_value, data, "GameResUpgradeReq_DEF")
	if err != nil {
		return err
	}
	*x = GameResUpgradeReq_DEF(value)
	return nil
}

func (GameResUpgradeReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{24, 0}
}

type GameResUpgradeResp_DEF int32

const (
	GameResUpgradeResp_ID GameResUpgradeResp_DEF = 14
)

var GameResUpgradeResp_DEF_name = map[int32]string{
	14: "ID",
}

var GameResUpgradeResp_DEF_value = map[string]int32{
	"ID": 14,
}

func (x GameResUpgradeResp_DEF) Enum() *GameResUpgradeResp_DEF {
	p := new(GameResUpgradeResp_DEF)
	*p = x
	return p
}

func (x GameResUpgradeResp_DEF) String() string {
	return proto.EnumName(GameResUpgradeResp_DEF_name, int32(x))
}

func (x *GameResUpgradeResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameResUpgradeResp_DEF_value, data, "GameResUpgradeResp_DEF")
	if err != nil {
		return err
	}
	*x = GameResUpgradeResp_DEF(value)
	return nil
}

func (GameResUpgradeResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{25, 0}
}

type LogoutReq_DEF int32

const (
	LogoutReq_ID LogoutReq_DEF = 5
)

var LogoutReq_DEF_name = map[int32]string{
	5: "ID",
}

var LogoutReq_DEF_value = map[string]int32{
	"ID": 5,
}

func (x LogoutReq_DEF) Enum() *LogoutReq_DEF {
	p := new(LogoutReq_DEF)
	*p = x
	return p
}

func (x LogoutReq_DEF) String() string {
	return proto.EnumName(LogoutReq_DEF_name, int32(x))
}

func (x *LogoutReq_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LogoutReq_DEF_value, data, "LogoutReq_DEF")
	if err != nil {
		return err
	}
	*x = LogoutReq_DEF(value)
	return nil
}

func (LogoutReq_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{26, 0}
}

type LogoutResp_DEF int32

const (
	LogoutResp_ID LogoutResp_DEF = 6
)

var LogoutResp_DEF_name = map[int32]string{
	6: "ID",
}

var LogoutResp_DEF_value = map[string]int32{
	"ID": 6,
}

func (x LogoutResp_DEF) Enum() *LogoutResp_DEF {
	p := new(LogoutResp_DEF)
	*p = x
	return p
}

func (x LogoutResp_DEF) String() string {
	return proto.EnumName(LogoutResp_DEF_name, int32(x))
}

func (x *LogoutResp_DEF) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LogoutResp_DEF_value, data, "LogoutResp_DEF")
	if err != nil {
		return err
	}
	*x = LogoutResp_DEF(value)
	return nil
}

func (LogoutResp_DEF) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{27, 0}
}

type LoginReq struct {
	Mobile               *string  `protobuf:"bytes,1,opt,name=mobile" json:"mobile,omitempty"`
	DeviceId             *string  `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Password             *string  `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Token                *string  `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetMobile() string {
	if m != nil && m.Mobile != nil {
		return *m.Mobile
	}
	return ""
}

func (m *LoginReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type LoginResp struct {
	Uid                  *int32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Session              *int32   `protobuf:"varint,2,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LoginResp) GetSession() int32 {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return 0
}

// 重置密码
type ResetReq struct {
	Mobile               *string  `protobuf:"bytes,1,req,name=mobile" json:"mobile,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,3,req,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetReq) Reset()         { *m = ResetReq{} }
func (m *ResetReq) String() string { return proto.CompactTextString(m) }
func (*ResetReq) ProtoMessage()    {}
func (*ResetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{2}
}

func (m *ResetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetReq.Unmarshal(m, b)
}
func (m *ResetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetReq.Marshal(b, m, deterministic)
}
func (m *ResetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetReq.Merge(m, src)
}
func (m *ResetReq) XXX_Size() int {
	return xxx_messageInfo_ResetReq.Size(m)
}
func (m *ResetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetReq proto.InternalMessageInfo

func (m *ResetReq) GetMobile() string {
	if m != nil && m.Mobile != nil {
		return *m.Mobile
	}
	return ""
}

func (m *ResetReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *ResetReq) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

type ResetResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResp) Reset()         { *m = ResetResp{} }
func (m *ResetResp) String() string { return proto.CompactTextString(m) }
func (*ResetResp) ProtoMessage()    {}
func (*ResetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{3}
}

func (m *ResetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResp.Unmarshal(m, b)
}
func (m *ResetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResp.Marshal(b, m, deterministic)
}
func (m *ResetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResp.Merge(m, src)
}
func (m *ResetResp) XXX_Size() int {
	return xxx_messageInfo_ResetResp.Size(m)
}
func (m *ResetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResp proto.InternalMessageInfo

type FastLoginReq struct {
	DeviceId             *string  `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Token                *string  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	Channel              *string  `protobuf:"bytes,3,req,name=channel" json:"channel,omitempty"`
	Imei                 *string  `protobuf:"bytes,4,opt,name=imei" json:"imei,omitempty"`
	Imsi                 *string  `protobuf:"bytes,5,opt,name=imsi" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FastLoginReq) Reset()         { *m = FastLoginReq{} }
func (m *FastLoginReq) String() string { return proto.CompactTextString(m) }
func (*FastLoginReq) ProtoMessage()    {}
func (*FastLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{4}
}

func (m *FastLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastLoginReq.Unmarshal(m, b)
}
func (m *FastLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastLoginReq.Marshal(b, m, deterministic)
}
func (m *FastLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastLoginReq.Merge(m, src)
}
func (m *FastLoginReq) XXX_Size() int {
	return xxx_messageInfo_FastLoginReq.Size(m)
}
func (m *FastLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FastLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_FastLoginReq proto.InternalMessageInfo

func (m *FastLoginReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *FastLoginReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *FastLoginReq) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *FastLoginReq) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *FastLoginReq) GetImsi() string {
	if m != nil && m.Imsi != nil {
		return *m.Imsi
	}
	return ""
}

type FastLoginResp struct {
	Uid                  *int32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Session              *int32   `protobuf:"varint,2,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FastLoginResp) Reset()         { *m = FastLoginResp{} }
func (m *FastLoginResp) String() string { return proto.CompactTextString(m) }
func (*FastLoginResp) ProtoMessage()    {}
func (*FastLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{5}
}

func (m *FastLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastLoginResp.Unmarshal(m, b)
}
func (m *FastLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastLoginResp.Marshal(b, m, deterministic)
}
func (m *FastLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastLoginResp.Merge(m, src)
}
func (m *FastLoginResp) XXX_Size() int {
	return xxx_messageInfo_FastLoginResp.Size(m)
}
func (m *FastLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FastLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_FastLoginResp proto.InternalMessageInfo

func (m *FastLoginResp) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *FastLoginResp) GetSession() int32 {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return 0
}

type GetVerifyCodeReq struct {
	Mobile               *string  `protobuf:"bytes,1,req,name=mobile" json:"mobile,omitempty"`
	Token                *string  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVerifyCodeReq) Reset()         { *m = GetVerifyCodeReq{} }
func (m *GetVerifyCodeReq) String() string { return proto.CompactTextString(m) }
func (*GetVerifyCodeReq) ProtoMessage()    {}
func (*GetVerifyCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{6}
}

func (m *GetVerifyCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVerifyCodeReq.Unmarshal(m, b)
}
func (m *GetVerifyCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVerifyCodeReq.Marshal(b, m, deterministic)
}
func (m *GetVerifyCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVerifyCodeReq.Merge(m, src)
}
func (m *GetVerifyCodeReq) XXX_Size() int {
	return xxx_messageInfo_GetVerifyCodeReq.Size(m)
}
func (m *GetVerifyCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVerifyCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVerifyCodeReq proto.InternalMessageInfo

func (m *GetVerifyCodeReq) GetMobile() string {
	if m != nil && m.Mobile != nil {
		return *m.Mobile
	}
	return ""
}

func (m *GetVerifyCodeReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type GetVerifyCodeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVerifyCodeResp) Reset()         { *m = GetVerifyCodeResp{} }
func (m *GetVerifyCodeResp) String() string { return proto.CompactTextString(m) }
func (*GetVerifyCodeResp) ProtoMessage()    {}
func (*GetVerifyCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{7}
}

func (m *GetVerifyCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVerifyCodeResp.Unmarshal(m, b)
}
func (m *GetVerifyCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVerifyCodeResp.Marshal(b, m, deterministic)
}
func (m *GetVerifyCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVerifyCodeResp.Merge(m, src)
}
func (m *GetVerifyCodeResp) XXX_Size() int {
	return xxx_messageInfo_GetVerifyCodeResp.Size(m)
}
func (m *GetVerifyCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVerifyCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVerifyCodeResp proto.InternalMessageInfo

type RegisterReq struct {
	Mobile               *string  `protobuf:"bytes,1,req,name=mobile" json:"mobile,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,3,req,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
	DeviceId             *string  `protobuf:"bytes,4,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Channel              *string  `protobuf:"bytes,5,opt,name=channel" json:"channel,omitempty"`
	Imei                 *string  `protobuf:"bytes,6,opt,name=imei" json:"imei,omitempty"`
	Imsi                 *string  `protobuf:"bytes,7,opt,name=imsi" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{8}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetMobile() string {
	if m != nil && m.Mobile != nil {
		return *m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegisterReq) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

func (m *RegisterReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *RegisterReq) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *RegisterReq) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *RegisterReq) GetImsi() string {
	if m != nil && m.Imsi != nil {
		return *m.Imsi
	}
	return ""
}

type RegisterResp struct {
	Uid                  *int32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Session              *int32   `protobuf:"varint,2,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{9}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *RegisterResp) GetSession() int32 {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return 0
}

type ConnectGameServerReq struct {
	Session              *string  `protobuf:"bytes,1,req,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectGameServerReq) Reset()         { *m = ConnectGameServerReq{} }
func (m *ConnectGameServerReq) String() string { return proto.CompactTextString(m) }
func (*ConnectGameServerReq) ProtoMessage()    {}
func (*ConnectGameServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{10}
}

func (m *ConnectGameServerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectGameServerReq.Unmarshal(m, b)
}
func (m *ConnectGameServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectGameServerReq.Marshal(b, m, deterministic)
}
func (m *ConnectGameServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectGameServerReq.Merge(m, src)
}
func (m *ConnectGameServerReq) XXX_Size() int {
	return xxx_messageInfo_ConnectGameServerReq.Size(m)
}
func (m *ConnectGameServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectGameServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectGameServerReq proto.InternalMessageInfo

func (m *ConnectGameServerReq) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

type ConnectGameServerResp struct {
	ServerTime           *int64   `protobuf:"varint,1,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectGameServerResp) Reset()         { *m = ConnectGameServerResp{} }
func (m *ConnectGameServerResp) String() string { return proto.CompactTextString(m) }
func (*ConnectGameServerResp) ProtoMessage()    {}
func (*ConnectGameServerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{11}
}

func (m *ConnectGameServerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectGameServerResp.Unmarshal(m, b)
}
func (m *ConnectGameServerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectGameServerResp.Marshal(b, m, deterministic)
}
func (m *ConnectGameServerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectGameServerResp.Merge(m, src)
}
func (m *ConnectGameServerResp) XXX_Size() int {
	return xxx_messageInfo_ConnectGameServerResp.Size(m)
}
func (m *ConnectGameServerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectGameServerResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectGameServerResp proto.InternalMessageInfo

func (m *ConnectGameServerResp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

type HeartbeatReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReq) Reset()         { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()    {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{12}
}

func (m *HeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReq.Unmarshal(m, b)
}
func (m *HeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReq.Merge(m, src)
}
func (m *HeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReq.Size(m)
}
func (m *HeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReq proto.InternalMessageInfo

type HeartbeatResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResp) Reset()         { *m = HeartbeatResp{} }
func (m *HeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResp) ProtoMessage()    {}
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{13}
}

func (m *HeartbeatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResp.Unmarshal(m, b)
}
func (m *HeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResp.Marshal(b, m, deterministic)
}
func (m *HeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResp.Merge(m, src)
}
func (m *HeartbeatResp) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResp.Size(m)
}
func (m *HeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResp proto.InternalMessageInfo

type GetServerTimeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServerTimeReq) Reset()         { *m = GetServerTimeReq{} }
func (m *GetServerTimeReq) String() string { return proto.CompactTextString(m) }
func (*GetServerTimeReq) ProtoMessage()    {}
func (*GetServerTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{14}
}

func (m *GetServerTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerTimeReq.Unmarshal(m, b)
}
func (m *GetServerTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerTimeReq.Marshal(b, m, deterministic)
}
func (m *GetServerTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerTimeReq.Merge(m, src)
}
func (m *GetServerTimeReq) XXX_Size() int {
	return xxx_messageInfo_GetServerTimeReq.Size(m)
}
func (m *GetServerTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerTimeReq proto.InternalMessageInfo

type GetServerTimeResp struct {
	ServerTime           *int64   `protobuf:"varint,1,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServerTimeResp) Reset()         { *m = GetServerTimeResp{} }
func (m *GetServerTimeResp) String() string { return proto.CompactTextString(m) }
func (*GetServerTimeResp) ProtoMessage()    {}
func (*GetServerTimeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{15}
}

func (m *GetServerTimeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerTimeResp.Unmarshal(m, b)
}
func (m *GetServerTimeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerTimeResp.Marshal(b, m, deterministic)
}
func (m *GetServerTimeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerTimeResp.Merge(m, src)
}
func (m *GetServerTimeResp) XXX_Size() int {
	return xxx_messageInfo_GetServerTimeResp.Size(m)
}
func (m *GetServerTimeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerTimeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerTimeResp proto.InternalMessageInfo

func (m *GetServerTimeResp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

type QuitGameServerReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGameServerReq) Reset()         { *m = QuitGameServerReq{} }
func (m *QuitGameServerReq) String() string { return proto.CompactTextString(m) }
func (*QuitGameServerReq) ProtoMessage()    {}
func (*QuitGameServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{16}
}

func (m *QuitGameServerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGameServerReq.Unmarshal(m, b)
}
func (m *QuitGameServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGameServerReq.Marshal(b, m, deterministic)
}
func (m *QuitGameServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGameServerReq.Merge(m, src)
}
func (m *QuitGameServerReq) XXX_Size() int {
	return xxx_messageInfo_QuitGameServerReq.Size(m)
}
func (m *QuitGameServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGameServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGameServerReq proto.InternalMessageInfo

type QuitGameServerResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGameServerResp) Reset()         { *m = QuitGameServerResp{} }
func (m *QuitGameServerResp) String() string { return proto.CompactTextString(m) }
func (*QuitGameServerResp) ProtoMessage()    {}
func (*QuitGameServerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{17}
}

func (m *QuitGameServerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGameServerResp.Unmarshal(m, b)
}
func (m *QuitGameServerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGameServerResp.Marshal(b, m, deterministic)
}
func (m *QuitGameServerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGameServerResp.Merge(m, src)
}
func (m *QuitGameServerResp) XXX_Size() int {
	return xxx_messageInfo_QuitGameServerResp.Size(m)
}
func (m *QuitGameServerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGameServerResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGameServerResp proto.InternalMessageInfo

type OnlineReq struct {
	Uid                  *int32   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	AccessServiceId      *int32   `protobuf:"varint,2,req,name=access_service_id,json=accessServiceId" json:"access_service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineReq) Reset()         { *m = OnlineReq{} }
func (m *OnlineReq) String() string { return proto.CompactTextString(m) }
func (*OnlineReq) ProtoMessage()    {}
func (*OnlineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{18}
}

func (m *OnlineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineReq.Unmarshal(m, b)
}
func (m *OnlineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineReq.Marshal(b, m, deterministic)
}
func (m *OnlineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineReq.Merge(m, src)
}
func (m *OnlineReq) XXX_Size() int {
	return xxx_messageInfo_OnlineReq.Size(m)
}
func (m *OnlineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineReq proto.InternalMessageInfo

func (m *OnlineReq) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *OnlineReq) GetAccessServiceId() int32 {
	if m != nil && m.AccessServiceId != nil {
		return *m.AccessServiceId
	}
	return 0
}

type OnlineResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineResp) Reset()         { *m = OnlineResp{} }
func (m *OnlineResp) String() string { return proto.CompactTextString(m) }
func (*OnlineResp) ProtoMessage()    {}
func (*OnlineResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{19}
}

func (m *OnlineResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineResp.Unmarshal(m, b)
}
func (m *OnlineResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineResp.Marshal(b, m, deterministic)
}
func (m *OnlineResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineResp.Merge(m, src)
}
func (m *OnlineResp) XXX_Size() int {
	return xxx_messageInfo_OnlineResp.Size(m)
}
func (m *OnlineResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineResp proto.InternalMessageInfo

type OfflineReq struct {
	Uid                  *int32   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineReq) Reset()         { *m = OfflineReq{} }
func (m *OfflineReq) String() string { return proto.CompactTextString(m) }
func (*OfflineReq) ProtoMessage()    {}
func (*OfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{20}
}

func (m *OfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineReq.Unmarshal(m, b)
}
func (m *OfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineReq.Marshal(b, m, deterministic)
}
func (m *OfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineReq.Merge(m, src)
}
func (m *OfflineReq) XXX_Size() int {
	return xxx_messageInfo_OfflineReq.Size(m)
}
func (m *OfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineReq proto.InternalMessageInfo

func (m *OfflineReq) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type OfflineResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineResp) Reset()         { *m = OfflineResp{} }
func (m *OfflineResp) String() string { return proto.CompactTextString(m) }
func (*OfflineResp) ProtoMessage()    {}
func (*OfflineResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{21}
}

func (m *OfflineResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineResp.Unmarshal(m, b)
}
func (m *OfflineResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineResp.Marshal(b, m, deterministic)
}
func (m *OfflineResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineResp.Merge(m, src)
}
func (m *OfflineResp) XXX_Size() int {
	return xxx_messageInfo_OfflineResp.Size(m)
}
func (m *OfflineResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineResp.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineResp proto.InternalMessageInfo

type CheckUpgradeReq struct {
	Version              *int32   `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Channel              *string  `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUpgradeReq) Reset()         { *m = CheckUpgradeReq{} }
func (m *CheckUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeReq) ProtoMessage()    {}
func (*CheckUpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{22}
}

func (m *CheckUpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeReq.Unmarshal(m, b)
}
func (m *CheckUpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeReq.Marshal(b, m, deterministic)
}
func (m *CheckUpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeReq.Merge(m, src)
}
func (m *CheckUpgradeReq) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeReq.Size(m)
}
func (m *CheckUpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeReq proto.InternalMessageInfo

func (m *CheckUpgradeReq) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CheckUpgradeReq) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

type CheckUpgradeResp struct {
	NewVersion           *int32   `protobuf:"varint,1,opt,name=new_version,json=newVersion" json:"new_version,omitempty"`
	UpgradeInfo          *string  `protobuf:"bytes,2,opt,name=upgrade_info,json=upgradeInfo" json:"upgrade_info,omitempty"`
	ForceClean           *bool    `protobuf:"varint,3,opt,name=force_clean,json=forceClean" json:"force_clean,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUpgradeResp) Reset()         { *m = CheckUpgradeResp{} }
func (m *CheckUpgradeResp) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeResp) ProtoMessage()    {}
func (*CheckUpgradeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{23}
}

func (m *CheckUpgradeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeResp.Unmarshal(m, b)
}
func (m *CheckUpgradeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeResp.Marshal(b, m, deterministic)
}
func (m *CheckUpgradeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeResp.Merge(m, src)
}
func (m *CheckUpgradeResp) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeResp.Size(m)
}
func (m *CheckUpgradeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeResp proto.InternalMessageInfo

func (m *CheckUpgradeResp) GetNewVersion() int32 {
	if m != nil && m.NewVersion != nil {
		return *m.NewVersion
	}
	return 0
}

func (m *CheckUpgradeResp) GetUpgradeInfo() string {
	if m != nil && m.UpgradeInfo != nil {
		return *m.UpgradeInfo
	}
	return ""
}

func (m *CheckUpgradeResp) GetForceClean() bool {
	if m != nil && m.ForceClean != nil {
		return *m.ForceClean
	}
	return false
}

type GameResUpgradeReq struct {
	Ver                  *int32   `protobuf:"varint,1,req,name=ver" json:"ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResUpgradeReq) Reset()         { *m = GameResUpgradeReq{} }
func (m *GameResUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*GameResUpgradeReq) ProtoMessage()    {}
func (*GameResUpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{24}
}

func (m *GameResUpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResUpgradeReq.Unmarshal(m, b)
}
func (m *GameResUpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResUpgradeReq.Marshal(b, m, deterministic)
}
func (m *GameResUpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResUpgradeReq.Merge(m, src)
}
func (m *GameResUpgradeReq) XXX_Size() int {
	return xxx_messageInfo_GameResUpgradeReq.Size(m)
}
func (m *GameResUpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResUpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameResUpgradeReq proto.InternalMessageInfo

func (m *GameResUpgradeReq) GetVer() int32 {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return 0
}

type GameResUpgradeResp struct {
	IsUpgrade            *bool    `protobuf:"varint,1,req,name=is_upgrade,json=isUpgrade" json:"is_upgrade,omitempty"`
	UpgradeUrl           *string  `protobuf:"bytes,2,opt,name=upgrade_url,json=upgradeUrl" json:"upgrade_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResUpgradeResp) Reset()         { *m = GameResUpgradeResp{} }
func (m *GameResUpgradeResp) String() string { return proto.CompactTextString(m) }
func (*GameResUpgradeResp) ProtoMessage()    {}
func (*GameResUpgradeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{25}
}

func (m *GameResUpgradeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResUpgradeResp.Unmarshal(m, b)
}
func (m *GameResUpgradeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResUpgradeResp.Marshal(b, m, deterministic)
}
func (m *GameResUpgradeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResUpgradeResp.Merge(m, src)
}
func (m *GameResUpgradeResp) XXX_Size() int {
	return xxx_messageInfo_GameResUpgradeResp.Size(m)
}
func (m *GameResUpgradeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResUpgradeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GameResUpgradeResp proto.InternalMessageInfo

func (m *GameResUpgradeResp) GetIsUpgrade() bool {
	if m != nil && m.IsUpgrade != nil {
		return *m.IsUpgrade
	}
	return false
}

func (m *GameResUpgradeResp) GetUpgradeUrl() string {
	if m != nil && m.UpgradeUrl != nil {
		return *m.UpgradeUrl
	}
	return ""
}

type LogoutReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{26}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

type LogoutResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{27}
}

func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.LoginReq_DEF", LoginReq_DEF_name, LoginReq_DEF_value)
	proto.RegisterEnum("pb.LoginResp_DEF", LoginResp_DEF_name, LoginResp_DEF_value)
	proto.RegisterEnum("pb.ResetReq_DEF", ResetReq_DEF_name, ResetReq_DEF_value)
	proto.RegisterEnum("pb.ResetResp_DEF", ResetResp_DEF_name, ResetResp_DEF_value)
	proto.RegisterEnum("pb.FastLoginReq_DEF", FastLoginReq_DEF_name, FastLoginReq_DEF_value)
	proto.RegisterEnum("pb.FastLoginResp_DEF", FastLoginResp_DEF_name, FastLoginResp_DEF_value)
	proto.RegisterEnum("pb.GetVerifyCodeReq_DEF", GetVerifyCodeReq_DEF_name, GetVerifyCodeReq_DEF_value)
	proto.RegisterEnum("pb.GetVerifyCodeResp_DEF", GetVerifyCodeResp_DEF_name, GetVerifyCodeResp_DEF_value)
	proto.RegisterEnum("pb.RegisterReq_DEF", RegisterReq_DEF_name, RegisterReq_DEF_value)
	proto.RegisterEnum("pb.RegisterResp_DEF", RegisterResp_DEF_name, RegisterResp_DEF_value)
	proto.RegisterEnum("pb.ConnectGameServerReq_DEF", ConnectGameServerReq_DEF_name, ConnectGameServerReq_DEF_value)
	proto.RegisterEnum("pb.ConnectGameServerResp_DEF", ConnectGameServerResp_DEF_name, ConnectGameServerResp_DEF_value)
	proto.RegisterEnum("pb.HeartbeatReq_DEF", HeartbeatReq_DEF_name, HeartbeatReq_DEF_value)
	proto.RegisterEnum("pb.HeartbeatResp_DEF", HeartbeatResp_DEF_name, HeartbeatResp_DEF_value)
	proto.RegisterEnum("pb.GetServerTimeReq_DEF", GetServerTimeReq_DEF_name, GetServerTimeReq_DEF_value)
	proto.RegisterEnum("pb.GetServerTimeResp_DEF", GetServerTimeResp_DEF_name, GetServerTimeResp_DEF_value)
	proto.RegisterEnum("pb.QuitGameServerReq_DEF", QuitGameServerReq_DEF_name, QuitGameServerReq_DEF_value)
	proto.RegisterEnum("pb.QuitGameServerResp_DEF", QuitGameServerResp_DEF_name, QuitGameServerResp_DEF_value)
	proto.RegisterEnum("pb.OnlineReq_DEF", OnlineReq_DEF_name, OnlineReq_DEF_value)
	proto.RegisterEnum("pb.OnlineResp_DEF", OnlineResp_DEF_name, OnlineResp_DEF_value)
	proto.RegisterEnum("pb.OfflineReq_DEF", OfflineReq_DEF_name, OfflineReq_DEF_value)
	proto.RegisterEnum("pb.OfflineResp_DEF", OfflineResp_DEF_name, OfflineResp_DEF_value)
	proto.RegisterEnum("pb.CheckUpgradeReq_DEF", CheckUpgradeReq_DEF_name, CheckUpgradeReq_DEF_value)
	proto.RegisterEnum("pb.CheckUpgradeResp_DEF", CheckUpgradeResp_DEF_name, CheckUpgradeResp_DEF_value)
	proto.RegisterEnum("pb.GameResUpgradeReq_DEF", GameResUpgradeReq_DEF_name, GameResUpgradeReq_DEF_value)
	proto.RegisterEnum("pb.GameResUpgradeResp_DEF", GameResUpgradeResp_DEF_name, GameResUpgradeResp_DEF_value)
	proto.RegisterEnum("pb.LogoutReq_DEF", LogoutReq_DEF_name, LogoutReq_DEF_value)
	proto.RegisterEnum("pb.LogoutResp_DEF", LogoutResp_DEF_name, LogoutResp_DEF_value)
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "pb.LoginResp")
	proto.RegisterType((*ResetReq)(nil), "pb.ResetReq")
	proto.RegisterType((*ResetResp)(nil), "pb.ResetResp")
	proto.RegisterType((*FastLoginReq)(nil), "pb.FastLoginReq")
	proto.RegisterType((*FastLoginResp)(nil), "pb.FastLoginResp")
	proto.RegisterType((*GetVerifyCodeReq)(nil), "pb.GetVerifyCodeReq")
	proto.RegisterType((*GetVerifyCodeResp)(nil), "pb.GetVerifyCodeResp")
	proto.RegisterType((*RegisterReq)(nil), "pb.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "pb.RegisterResp")
	proto.RegisterType((*ConnectGameServerReq)(nil), "pb.ConnectGameServerReq")
	proto.RegisterType((*ConnectGameServerResp)(nil), "pb.ConnectGameServerResp")
	proto.RegisterType((*HeartbeatReq)(nil), "pb.HeartbeatReq")
	proto.RegisterType((*HeartbeatResp)(nil), "pb.HeartbeatResp")
	proto.RegisterType((*GetServerTimeReq)(nil), "pb.GetServerTimeReq")
	proto.RegisterType((*GetServerTimeResp)(nil), "pb.GetServerTimeResp")
	proto.RegisterType((*QuitGameServerReq)(nil), "pb.QuitGameServerReq")
	proto.RegisterType((*QuitGameServerResp)(nil), "pb.QuitGameServerResp")
	proto.RegisterType((*OnlineReq)(nil), "pb.OnlineReq")
	proto.RegisterType((*OnlineResp)(nil), "pb.OnlineResp")
	proto.RegisterType((*OfflineReq)(nil), "pb.OfflineReq")
	proto.RegisterType((*OfflineResp)(nil), "pb.OfflineResp")
	proto.RegisterType((*CheckUpgradeReq)(nil), "pb.CheckUpgradeReq")
	proto.RegisterType((*CheckUpgradeResp)(nil), "pb.CheckUpgradeResp")
	proto.RegisterType((*GameResUpgradeReq)(nil), "pb.GameResUpgradeReq")
	proto.RegisterType((*GameResUpgradeResp)(nil), "pb.GameResUpgradeResp")
	proto.RegisterType((*LogoutReq)(nil), "pb.LogoutReq")
	proto.RegisterType((*LogoutResp)(nil), "pb.LogoutResp")
}

func init() { proto.RegisterFile("access.proto", fileDescriptor_a098e900d2c3a6f2) }

var fileDescriptor_a098e900d2c3a6f2 = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xef, 0x49, 0xd2, 0xa6, 0x56, 0x8b, 0xac, 0x56, 0x05, 0xba, 0x5c, 0x0a, 0x87,
	0x9e, 0xb8, 0x73, 0x48, 0x69, 0x09, 0xaa, 0x54, 0xe1, 0xd2, 0x8a, 0x9b, 0xe5, 0xda, 0x93, 0x74,
	0x69, 0xb2, 0x6b, 0xbc, 0x4e, 0x4a, 0x6f, 0x08, 0x0e, 0xdc, 0x39, 0xc0, 0xdf, 0xe2, 0x27, 0xa1,
	0xdd, 0xb5, 0x1d, 0xaf, 0x9b, 0x22, 0xa1, 0x8a, 0x9b, 0xe7, 0xc3, 0x6f, 0xde, 0xbe, 0xb7, 0x63,
	0x43, 0x2f, 0x08, 0x43, 0x14, 0xe2, 0x20, 0x4e, 0x78, 0xca, 0x1d, 0x3b, 0xbe, 0xdc, 0xee, 0x89,
	0x34, 0x99, 0x87, 0xa9, 0xce, 0x90, 0x2f, 0x16, 0xb4, 0x4f, 0xf8, 0x84, 0x32, 0x0f, 0x3f, 0x39,
	0x8f, 0xa0, 0x39, 0xe3, 0x97, 0x74, 0x8a, 0xae, 0xf5, 0xd4, 0xda, 0xef, 0x78, 0x59, 0xe4, 0xec,
	0x40, 0x27, 0xc2, 0x05, 0x0d, 0xd1, 0xa7, 0x91, 0x6b, 0xab, 0x52, 0x5b, 0x27, 0x46, 0x91, 0xb3,
	0x0d, 0xed, 0x38, 0x10, 0xe2, 0x86, 0x27, 0x91, 0x5b, 0xd3, 0xb5, 0x3c, 0x76, 0x36, 0xa1, 0x91,
	0xf2, 0x6b, 0x64, 0x6e, 0x5d, 0x15, 0x74, 0x40, 0xfa, 0x50, 0x3b, 0x7c, 0x7d, 0xe4, 0x34, 0xc1,
	0x1e, 0x1d, 0x0e, 0x2c, 0x72, 0x04, 0x9d, 0x8c, 0x81, 0x88, 0x9d, 0x01, 0xd4, 0xe6, 0x34, 0x52,
	0xf3, 0x1b, 0x9e, 0x7c, 0x74, 0x5c, 0x68, 0x09, 0x14, 0x82, 0x72, 0xa6, 0x46, 0x37, 0xbc, 0x3c,
	0x34, 0x71, 0x6c, 0xc2, 0xa0, 0xed, 0xa1, 0xc0, 0xb4, 0x7a, 0x12, 0xbb, 0x74, 0x92, 0x32, 0x59,
	0x5b, 0x55, 0x96, 0x64, 0x9f, 0x40, 0x77, 0x81, 0x09, 0x1d, 0xdf, 0xfa, 0x21, 0x8f, 0xd0, 0xad,
	0xa9, 0x32, 0xe8, 0xd4, 0x90, 0x47, 0x68, 0xce, 0xdb, 0x24, 0xdb, 0xd0, 0xc9, 0xe6, 0x89, 0xd8,
	0xac, 0x6d, 0x91, 0x1f, 0x16, 0xf4, 0x8e, 0x02, 0x91, 0x16, 0xd2, 0x1a, 0x12, 0x6a, 0x4e, 0x4b,
	0x09, 0x0b, 0x99, 0x34, 0x25, 0x1d, 0xc8, 0x83, 0x87, 0x57, 0x01, 0x63, 0x38, 0xcd, 0xb8, 0xe4,
	0xa1, 0xe3, 0x40, 0x9d, 0xce, 0x90, 0x66, 0xaa, 0xaa, 0x67, 0x9d, 0x13, 0xd4, 0x6d, 0xe4, 0x39,
	0x41, 0x4d, 0x52, 0x35, 0xf2, 0x16, 0xfa, 0x25, 0x4e, 0x0f, 0x11, 0xbb, 0x4e, 0x4e, 0x61, 0x70,
	0x8c, 0xe9, 0x45, 0x21, 0xce, 0xdf, 0x44, 0x5f, 0x79, 0x3c, 0x13, 0xb0, 0x45, 0x08, 0x6c, 0x54,
	0x00, 0xab, 0xaa, 0xb6, 0xc9, 0x6f, 0x0b, 0xba, 0x1e, 0x4e, 0xa8, 0x48, 0x31, 0xf9, 0x5f, 0x2e,
	0x9b, 0x4e, 0xd5, 0x2b, 0x4e, 0x95, 0x3c, 0xd1, 0x42, 0xdf, 0xf1, 0xa4, 0xb9, 0xc2, 0x93, 0xd6,
	0x7d, 0x9e, 0x74, 0xc8, 0x08, 0x7a, 0xcb, 0x13, 0x3d, 0xc4, 0x12, 0x20, 0xaf, 0x60, 0x73, 0xc8,
	0x19, 0xc3, 0x30, 0x3d, 0x0e, 0x66, 0x78, 0x86, 0xc9, 0x42, 0xab, 0x54, 0x02, 0xd0, 0x32, 0xad,
	0x06, 0xd8, 0x27, 0xc7, 0xb0, 0xb5, 0x02, 0x40, 0xc4, 0x52, 0x33, 0xa1, 0x22, 0x3f, 0xa5, 0x33,
	0xfd, 0x71, 0xa8, 0x79, 0xa0, 0x53, 0xef, 0xe9, 0xac, 0xb2, 0x19, 0xcf, 0xc9, 0x2e, 0xf4, 0xde,
	0x60, 0x90, 0xa4, 0x97, 0x18, 0xc8, 0x6d, 0x34, 0xcb, 0x11, 0x79, 0x0c, 0xfd, 0x52, 0xb9, 0x6a,
	0x33, 0x92, 0x3d, 0x75, 0xb7, 0xce, 0x0a, 0xf8, 0x3b, 0x10, 0x1f, 0xc9, 0x50, 0xdd, 0x96, 0x72,
	0xcb, 0x3f, 0xd3, 0xbc, 0x96, 0x57, 0xee, 0xdd, 0x9c, 0x9a, 0x6a, 0x99, 0x3d, 0x8c, 0x3c, 0x03,
	0xa7, 0xda, 0x53, 0x25, 0xcc, 0xc9, 0x07, 0xe8, 0x9c, 0xb2, 0x29, 0x65, 0x6a, 0x0b, 0x0a, 0x07,
	0xed, 0xdc, 0xc1, 0x17, 0xb0, 0xa1, 0xbf, 0xc2, 0xbe, 0xe4, 0x52, 0x7c, 0x46, 0x65, 0x7d, 0x5d,
	0x17, 0xce, 0x74, 0x7e, 0x14, 0x99, 0xc8, 0x9f, 0xc9, 0x0e, 0x40, 0x8e, 0x5c, 0x1d, 0x7b, 0x4b,
	0x0e, 0x00, 0x4e, 0xc7, 0xe3, 0x7b, 0xe7, 0x92, 0x35, 0xdd, 0xde, 0x52, 0xed, 0x5f, 0x2d, 0xb2,
	0x0b, 0xdd, 0xa2, 0x5f, 0xc4, 0x66, 0xf9, 0x9b, 0x45, 0xce, 0x61, 0x7d, 0x78, 0x85, 0xe1, 0xf5,
	0x79, 0x3c, 0x49, 0x02, 0xbd, 0xd1, 0x2e, 0xb4, 0x16, 0x98, 0x14, 0x57, 0xa7, 0xe1, 0xe5, 0x61,
	0x79, 0x11, 0x6c, 0x63, 0x11, 0x4c, 0xd8, 0x9f, 0x16, 0xf9, 0x6e, 0xc1, 0xc0, 0xc4, 0xd5, 0x56,
	0x31, 0xbc, 0xf1, 0x97, 0xe0, 0xf2, 0x62, 0x03, 0xc3, 0x9b, 0x8b, 0x0c, 0x7f, 0x0f, 0x7a, 0x73,
	0xdd, 0xef, 0x53, 0x36, 0xe6, 0xd9, 0x90, 0x6e, 0x96, 0x1b, 0xb1, 0x31, 0x97, 0x18, 0x63, 0x9e,
	0x84, 0xe8, 0x87, 0x53, 0x0c, 0x98, 0xfa, 0xf7, 0xb4, 0x3d, 0x50, 0xa9, 0xa1, 0xcc, 0x98, 0x4c,
	0x7e, 0x59, 0xe4, 0x25, 0x6c, 0x48, 0x1f, 0x3d, 0x14, 0xa5, 0x23, 0x0e, 0xa0, 0xb6, 0xc0, 0x24,
	0x97, 0x6d, 0x81, 0x89, 0xa9, 0x72, 0x9f, 0x84, 0xe0, 0x54, 0xdf, 0x12, 0xb1, 0xb3, 0x0b, 0x40,
	0x85, 0x9f, 0xd1, 0x51, 0x6f, 0xb7, 0xbd, 0x0e, 0xcd, 0x5b, 0x24, 0xb7, 0x9c, 0xfe, 0x3c, 0xc9,
	0x25, 0x82, 0x2c, 0x75, 0x9e, 0x4c, 0xcd, 0x21, 0x6b, 0xf2, 0x5f, 0x72, 0xc2, 0x27, 0x7c, 0x7e,
	0x77, 0x5d, 0x1a, 0xf2, 0x0e, 0xe4, 0xb5, 0xea, 0x1d, 0x68, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0xbc, 0xed, 0xa5, 0xe0, 0x07, 0x00, 0x00,
}
