// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mapping.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mapping struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Mapping) Reset()         { *m = Mapping{} }
func (m *Mapping) String() string { return proto.CompactTextString(m) }
func (*Mapping) ProtoMessage()    {}
func (*Mapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_92521b297e0ff076, []int{0}
}

var extRange_Mapping = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Mapping) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Mapping
}

func (m *Mapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mapping.Unmarshal(m, b)
}
func (m *Mapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mapping.Marshal(b, m, deterministic)
}
func (m *Mapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mapping.Merge(m, src)
}
func (m *Mapping) XXX_Size() int {
	return xxx_messageInfo_Mapping.Size(m)
}
func (m *Mapping) XXX_DiscardUnknown() {
	xxx_messageInfo_Mapping.DiscardUnknown(m)
}

var xxx_messageInfo_Mapping proto.InternalMessageInfo

var E_LoginReq = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*LoginReq)(nil),
	Field:         1,
	Name:          "pb.login_req",
	Tag:           "bytes,1,opt,name=login_req",
	Filename:      "mapping.proto",
}

var E_LoginResp = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*LoginResp)(nil),
	Field:         2,
	Name:          "pb.login_resp",
	Tag:           "bytes,2,opt,name=login_resp",
	Filename:      "mapping.proto",
}

var E_ConnectGameServerReq = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*ConnectGameServerReq)(nil),
	Field:         40,
	Name:          "pb.connect_game_server_req",
	Tag:           "bytes,40,opt,name=connect_game_server_req",
	Filename:      "mapping.proto",
}

var E_ConnectGameServerResp = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*ConnectGameServerResp)(nil),
	Field:         41,
	Name:          "pb.connect_game_server_resp",
	Tag:           "bytes,41,opt,name=connect_game_server_resp",
	Filename:      "mapping.proto",
}

var E_QuitGameServerReq = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*QuitGameServerReq)(nil),
	Field:         110,
	Name:          "pb.quit_game_server_req",
	Tag:           "bytes,110,opt,name=quit_game_server_req",
	Filename:      "mapping.proto",
}

var E_NotificationEvent = &proto.ExtensionDesc{
	ExtendedType:  (*Mapping)(nil),
	ExtensionType: (*NotificationEvent)(nil),
	Field:         1100,
	Name:          "pb.notification_event",
	Tag:           "bytes,1100,opt,name=notification_event",
	Filename:      "mapping.proto",
}

func init() {
	proto.RegisterType((*Mapping)(nil), "pb.Mapping")
	proto.RegisterExtension(E_LoginReq)
	proto.RegisterExtension(E_LoginResp)
	proto.RegisterExtension(E_ConnectGameServerReq)
	proto.RegisterExtension(E_ConnectGameServerResp)
	proto.RegisterExtension(E_QuitGameServerReq)
	proto.RegisterExtension(E_NotificationEvent)
}

func init() { proto.RegisterFile("mapping.proto", fileDescriptor_92521b297e0ff076) }

var fileDescriptor_92521b297e0ff076 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x2f, 0x76, 0x59, 0x07, 0xae, 0x6e, 0x58, 0x77, 0x12, 0x4f, 0xd3, 0x43, 0x0f,
	0x1e, 0x04, 0x73, 0x15, 0xf1, 0xa2, 0x82, 0xd9, 0x55, 0x28, 0x5d, 0x78, 0x96, 0x40, 0xf3, 0x92,
	0x36, 0xd9, 0xce, 0xfd, 0x03, 0xfd, 0xa3, 0x24, 0xe9, 0x86, 0x5b, 0xad, 0xec, 0xf6, 0xde, 0x8f,
	0xef, 0xfb, 0xf1, 0x91, 0x89, 0x2c, 0xb4, 0x16, 0x58, 0x66, 0xba, 0x51, 0x56, 0x25, 0xa1, 0x5e,
	0x2f, 0xe2, 0x82, 0x73, 0x30, 0xa6, 0x23, 0x8b, 0x98, 0x2b, 0x29, 0x15, 0x76, 0xdf, 0xcd, 0x05,
	0x39, 0x7b, 0xeb, 0x0a, 0x77, 0x51, 0x14, 0x9c, 0xb7, 0x6d, 0xdb, 0x86, 0xf4, 0x81, 0x8c, 0x2a,
	0x55, 0x0a, 0xcc, 0x1b, 0xa8, 0x93, 0x71, 0xa6, 0xd7, 0xd9, 0x2e, 0x93, 0x06, 0xd7, 0xc1, 0x72,
	0x7c, 0x1f, 0x3b, 0xf4, 0xea, 0x12, 0x0c, 0x6a, 0x16, 0x55, 0xbb, 0x8b, 0x3e, 0x12, 0xb2, 0xef,
	0x19, 0x7d, 0x5c, 0x0c, 0x7d, 0x71, 0x72, 0x50, 0x34, 0x9a, 0x8d, 0xaa, 0xfd, 0x49, 0x3f, 0xc9,
	0x25, 0x57, 0x88, 0xc0, 0x6d, 0x5e, 0x16, 0x12, 0x72, 0x03, 0xcd, 0x16, 0x9a, 0xbf, 0x03, 0x96,
	0xde, 0x93, 0x3a, 0xf4, 0xd4, 0xe5, 0x5f, 0x0a, 0x09, 0x2b, 0x9f, 0x76, 0x63, 0x66, 0x7c, 0x80,
	0xd2, 0x9c, 0xa4, 0xc3, 0xf6, 0xfe, 0xcc, 0x5b, 0xaf, 0xbf, 0xfa, 0x47, 0x6f, 0x34, 0x9b, 0xf3,
	0x21, 0x4c, 0x57, 0x64, 0x56, 0x6f, 0xc4, 0x89, 0xed, 0xe8, 0xe5, 0x73, 0x87, 0x3e, 0x36, 0xa2,
	0x37, 0x7c, 0x5a, 0xf7, 0x11, 0x65, 0x24, 0x41, 0x65, 0xc5, 0x97, 0xe0, 0x85, 0x15, 0x0a, 0x73,
	0xd8, 0x02, 0xda, 0x63, 0xe5, 0x77, 0xf4, 0xeb, 0x7c, 0x3f, 0xc8, 0x3e, 0xbb, 0x28, 0x9b, 0x62,
	0x1f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0x1d, 0x69, 0x7d, 0x1f, 0x02, 0x00, 0x00,
}
